name: "TEST"

on:
  pull_request:
    branches:
      - actions

jobs:
  chrome-publish:
    name: "Pre Release Extension"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Development Branch"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get commit SHA
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "Build and Test"
        run: |
          cd browser-extension/plugin
          ls
          pwd
          npm install
          npm run build
          zip extension.zip ./dist/ -r

      - name: "Upload extension.zip as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: extension
          path: browser-extension/plugin/extension.zip

      # - name: Create PR Comment with Artifact Link
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     artifact_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/extension"
      #     comment_body="You can download the extension artifact [here](${artifact_url})."
      #     curl -s -H "Authorization: token $GITHUB_TOKEN" -X POST -d "{\"body\":\"$comment_body\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
      